//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public long ContactNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Qualification { get; set; }
        public string SkillSet { get; set; }
        public bool Experience { get; set; }
        public string Reference { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public byte[] resume1 { get; set; }
    }
}
